### ISSUE TITLE
FEATURE: Media container update

### ISSUE THREAD

**Issue by dgonzals** [bmihaila/twitter-rss-scraper-google-apps-script#7]
Can this be updated on main-script.js? Reference - https://github.com/ciderpunx/twitrssme/commit/66e06160fcd816e5d91135f629625a3c949cc86e . It would be greatly appreciated. Thank you.

**Comment by bmihaila** [comment]
It took a while to understand what you wanted with the media container because all the media is added as a link to the RSS already. So no content is missed. A little bit more description would have helped.

Anyways, this issue gave me the idea https://github.com/ciderpunx/twitrssme/issues/15 that it is about having the preview images for media embedded in the HTML of the RSS. 
After some refactoring to have separate RSS title and the RSS body content, the media container preview is now embedded in the body with commit 6c1c91c04f169ada10d8d934e4dba94f764da969

Reopen the issue if there are bugs with it or something is still missing.
